<?php
return [
    'access' =>[
        'du_an-index'  =>'index_du_an',
        'du_an-show'  =>'show_du_an',
        'du_an-add'  =>'add_du_an',
        'du_an-edit'  =>'edit_du_an',
        'du_an-update'  =>'edit_du_an',
        'du_an-delete'  =>'delete_du_an',

        'template-index'  =>'index_template',
        'template-show'  =>'show_template',
        'template-add'  =>'add_template',
        'template-edit'  =>'edit_template',
        'template-update'  =>'edit_template',
        'template-delete'  =>'delete_template',

        'template-preview-index'  =>'index_template_preview',
        'template-preview-show'  =>'show_template_preview',
        'template-preview-add'  =>'add_template_preview',
        'template-preview-edit'  =>'edit_template_preview',
        'template-preview-update'  =>'edit_template_preview',
        'template-preview-delete'  =>'delete_template_preview',

        'project-index'  =>'index_project',
        'project-show'  =>'show_project',
        'project-add'  =>'add_project',
        'project-edit'  =>'edit_project',
        'project-update'  =>'edit_project',
        'project-delete'  =>'delete_project',

        'gadev-index'  =>'index_gadev',
        'gadev-show'  =>'show_gadev',
        'gadev-add'  =>'add_gadev',
        'gadev-edit'  =>'edit_gadev',
        'gadev-update'  =>'edit_gadev',
        'gadev-delete'  =>'delete_gadev',

        'ga-index'  =>'index_ga',
        'ga-show'  =>'show_ga',
        'ga-add'  =>'add_ga',
        'ga-edit'  =>'edit_ga',
        'ga-update'  =>'edit_ga',
        'ga-delete'  =>'delete_ga',

        'dev-index'  =>'index_dev',
        'dev-show'  =>'show_dev',
        'dev-add'  =>'add_dev',
        'dev-edit'  =>'edit_dev',
        'dev-update'  =>'edit_dev',
        'dev-delete'  =>'delete_dev',

        'dev_amazon-index'  =>'index_dev_amazon',
        'dev_amazon-show'  =>'show_dev_amazon',
        'dev_amazon-add'  =>'add_dev_amazon',
        'dev_amazon-edit'  =>'edit_dev_amazon',
        'dev_amazon-update'  =>'edit_dev_amazon',
        'dev_amazon-delete'  =>'delete_dev_amazon',

        'dev_samsung-index'  =>'index_dev_samsung',
        'dev_samsung-show'  =>'show_dev_samsung',
        'dev_samsung-add'  =>'add_dev_samsung',
        'dev_samsung-edit'  =>'edit_dev_samsung',
        'dev_samsung-update'  =>'edit_dev_samsung',
        'dev_samsung-delete'  =>'delete_dev_samsung',

        'dev_xiaomi-index'  =>'index_dev_xiaomi',
        'dev_xiaomi-show'  =>'show_dev_xiaomi',
        'dev_xiaomi-add'  =>'add_dev_xiaomi',
        'dev_xiaomi-edit'  =>'edit_dev_xiaomi',
        'dev_xiaomi-update'  =>'edit_dev_xiaomi',
        'dev_xiaomi-delete'  =>'delete_dev_xiaomi',

        'dev_oppo-index'  =>'index_dev_oppo',
        'dev_oppo-show'  =>'show_dev_oppo',
        'dev_oppo-add'  =>'add_dev_oppo',
        'dev_oppo-edit'  =>'edit_dev_oppo',
        'dev_oppo-update'  =>'edit_dev_oppo',
        'dev_oppo-delete'  =>'delete_dev_oppo',

        'dev_vivo-index'  =>'index_dev_vivo',
        'dev_vivo-show'  =>'show_dev_vivo',
        'dev_vivo-add'  =>'add_dev_vivo',
        'dev_vivo-edit'  =>'edit_dev_vivo',
        'dev_vivo-update'  =>'edit_dev_vivo',
        'dev_vivo-delete'  =>'delete_dev_vivo',

        'dev_huawei-index'  =>'index_dev_huawei',
        'dev_huawei-show'  =>'show_dev_huawei',
        'dev_huawei-add'  =>'add_dev_huawei',
        'dev_huawei-edit'  =>'edit_dev_huawei',
        'dev_huawei-update'  =>'edit_dev_huawei',
        'dev_huawei-delete'  =>'delete_dev_huawei',

        'user-index'  =>'index_user',
        'user-show'  =>'show_user',
        'user-add'  =>'add_user',
        'user-edit'  =>'edit_user',
        'user-update'  =>'edit_user',
        'user-delete'  =>'delete_user',

        'vai_tro-index'  =>'index_vai_tro',
        'vai_tro-show'  =>'show_vai_tro',
        'vai_tro-add'  =>'add_vai_tro',
        'vai_tro-edit'  =>'edit_vai_tro',
        'vai_tro-update'  =>'edit_vai_tro',
        'vai_tro-delete'  =>'delete_vai_tro',

        'phan_quyen-index'  =>'index_phan_quyen',
        'phan_quyen-show'  =>'show_phan_quyen',
        'phan_quyen-add'  =>'add_phan_quyen',
        'phan_quyen-edit'  =>'edit_phan_quyen',
        'phan_quyen-update'  =>'edit_phan_quyen',
        'phan_quyen-delete'  =>'delete_phan_quyen',

        'khosim-index'  =>'index_khosim',
        'khosim-show'  =>'show_khosim',
        'khosim-add'  =>'add_khosim',
        'khosim-edit'  =>'edit_khosim',
        'khosim-update'  =>'edit_khosim',
        'khosim-delete'  =>'delete_khosim',

        'cocsim-index'  =>'index_cocsim',
        'cocsim-show'  =>'show_cocsim',
        'cocsim-add'  =>'add_cocsim',
        'cocsim-edit'  =>'edit_cocsim',
        'cocsim-update'  =>'edit_cocsim',
        'cocsim-delete'  =>'delete_cocsim',

        'hub-index'  =>'index_hub',
        'hub-show'  =>'show_hub',
        'hub-add'  =>'add_hub',
        'hub-edit'  =>'edit_hub',
        'hub-update'  =>'edit_hub',
        'hub-delete'  =>'delete_hub',

        'sms-index'  =>'index_sms',
        'sms-show'  =>'show_sms',
        'sms-add'  =>'add_sms',
        'sms-edit'  =>'edit_sms',
        'sms-update'  =>'edit_sms',
        'sms-delete'  =>'delete_sms',

        'mail_manage-index'  =>'index_mail_manage',
        'mail_manage-show'  =>'show_mail_manage',
        'mail_manage-add'  =>'add_mail_manage',
        'mail_manage-edit'  =>'edit_mail_manage',
        'mail_manage-update'  =>'edit_mail_manage',
        'mail_manage-delete'  =>'delete_mail_manage',

        'mail_parent-index'  =>'index_mail_parent',
        'mail_parent-show'  =>'show_mail_parent',
        'mail_parent-add'  =>'add_mail_parent',
        'mail_parent-edit'  =>'edit_mmail_parent',
        'mail_parent-update'  =>'edit_mail_parent',
        'mail_parent-delete'  =>'delete_mail_parent',

        'mail_reg-index'  =>'index_mail_reg',
        'mail_reg-show'  =>'show_mail_reg',
        'mail_reg-add'  =>'add_mail_reg',
        'mail_reg-edit'  =>'edit_mail_reg',
        'mail_reg-update'  =>'edit_mail_reg',
        'mail_reg-delete'  =>'delete_mail_reg',

        'device-index'  =>'index_device',
        'device-show'  =>'show_device',
        'device-add'  =>'add_device',
        'device-edit'  =>'edit_device',
        'device-update'  =>'edit_device',
        'device-delete'  =>'delete_device',

        'script-index'  =>'index_script',
        'script-show'  =>'show_script',
        'script-add'  =>'add_script',
        'script-edit'  =>'edit_script',
        'script-update'  =>'edit_script',
        'script-delete'  =>'delete_script',

        'keystore-index'  =>'index_keystore',
        'keystore-show'  =>'show_keystore',
        'keystore-add'  =>'add_keystore',
        'keystore-edit'  =>'edit_keystore',
        'keystore-update'  =>'edit_keystore',
        'keystore-delete'  =>'delete_keystore',

    ],


    'table-module' => [
        'Dự án','Template','Project','Gadev','Dev','Dev Amazon','Dev SamSung','Dev Xiaomi','Dev Oppo','Dev Vivo','Dev Huawei','Ga',
        'User','Vai trò', 'Phân quyền',
        'khosim','cocsim','sms','hub','Mail Manage', 'Mail Parent','Mail Reg',
        'Device','Script', 'Keystore',
        'Template Preview'
    ],
    'module-child' =>[
        'Index','Show','Add','Edit','Delete'
    ]
];
